name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate script syntax
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          mkdir -p output
          echo "Criando uma report" > output/report.txt
          zip -r report.zip output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip