name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate script syntax
        run: |
          if bash -n status-check.sh; then
            echo "::notice::Syntax is valid"
          else
            echo "::error::Syntax failed"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests"
          echo "::warning::Simulated test run"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          mkdir -p output
          echo "Criando uma report" > output/report.txt
          zip -r report.zip output

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Add job summary
        run: |
          echo "Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- OS: \`${{ runner.os }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Steps: validate → test → package" >> $GITHUB_STEP_SUMMARY
          echo "- [Download artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY