name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Simulate deploy
        run: echo "Deploying to $PROD_DOMAIN"
        env:
          PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}